In [1]:

import numpy as np
import pandas as pd 

In [2]:

data = pd.read_csv('Churn_Modelling.csv')

In [3]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225     Spain  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850       NaN  Female  43.0   
5          6    15574012       Chu          645     Spain    Male  44.0   
6          7    15592531  Bartlett          619    France    Male  50.0   
7          8    15656148    Obinna          376   Germany     NaN  29.0   
8          9    15792365        He          501    France    Male  44.0   
9         10    15592389        H?          684    France    Male  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [7]:
data.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [8]:
data.describe()

RowNumber    CustomerId  CreditScore          Age        Tenure  \
count  10000.00000  1.000000e+04  10000.00000  9999.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.48290    38.924892      5.012800   
std     2886.89568  7.193619e+04     96.72014    10.486670      2.892174   
min        1.00000  1.556570e+07    225.00000    18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.00000    32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.00000    37.000000      5.000000   
75%     7500.25000  1.575323e+07    717.25000    44.000000      7.000000   
max    10000.00000  1.581569e+07    850.00000    92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count    9999.000000   10000.000000  10000.00000    10000.000000   
mean    76483.536070       1.530200      0.70550        0.515100   
std     62400.186375       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97188.620000       1.000000      1.00000        1.000000   
75%    127646.040000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

# Handling missing values

In [9]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance             True
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [10]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
data['Geography'].unique()#categorical replace with mode

array(['France', 'Spain', nan, 'Germany'], dtype=object)

In [12]:
data['Gender'].unique()#categorical replace with mode

array(['Female', 'Male', nan], dtype=object)

In [13]:
data['Geography'].fillna(data['Geography'].mode()[0], inplace= True)
data['Gender'].fillna(data['Gender'].mode()[0], inplace= True)
data['Age'].fillna(data['Age'].mean(), inplace= True)
data['Balance'].fillna(data['Balance'].median(), inplace= True)

In [14]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [15]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [16]:
data['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [17]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

In [18]:
le = LabelEncoder()
data['Gender']= le.fit_transform(data['Gender'])
data['Geography']= le.fit_transform(data['Geography'])

In [19]:
data['Gender'].unique()

array([0, 1])

In [20]:
data['Geography'].unique()

array([0, 2, 1])

In [17]:
data

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender   Age  \
0             1    15634602   Hargrave          619          0       0  42.0   
1             2    15647311       Hill          225          2       0  41.0   
2             3    15619304       Onio          629          0       0  42.0   
3             4    15701354       Boni          699          0       0  39.0   
4             5    15737888   Mitchell          850          0       0  43.0   
...         ...         ...        ...          ...        ...     ...   ...   
9995       9996    15606229   Obijiaku          771          0       1  39.0   
9996       9997    15569892  Johnstone          516          0       1  35.0   
9997       9998    15584532        Liu          709          0       0  36.0   
9998       9999    15682355  Sabbatini          772          1       1  42.0   
9999      10000    15628319     Walker          792          0       0  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [20]:
type(data)

pandas.core.frame.DataFrame

In [18]:
#split our data into dependent and indent variables
x= data.iloc[:,3:13].values

In [19]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [20]:
type(x)

numpy.ndarray

In [21]:
x.shape

(10000, 10)

In [22]:
y= data.iloc[:,13].values

In [23]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [24]:
y.shape

(10000,)

In [25]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z= one.fit_transform(x[:,1:2]).toarray()

In [26]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
x = np.delete(x,1,axis=1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [28]:
x.shape

(10000, 9)

In [29]:
x = np.concatenate((z,x),axis=1)
x.shape

(10000, 12)

In [30]:
x[1]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 2.2500000e+02,
       0.0000000e+00, 4.1000000e+01, 1.0000000e+00, 8.3807860e+04,
       1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1254258e+05])

In [31]:
#spliting into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2,random_state=0)

In [32]:
x_train.shape

(8000, 12)

In [33]:
print(x_train.shape)#training input
print(x_test.shape)#testing input
print(y_train.shape)#training output
print(y_test.shape)#testing output

(8000, 12)
(2000, 12)
(8000,)
(2000,)


In [53]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.fit_transform(x_test)

In [54]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])